# Anycable
anycable_redis_url: redis://127.0.0.1:6379/1
anycable_rpc_host: 127.0.0.1:50051

# DynamoDB config
dynamodb_tooling_jobs_table: tooling_jobs
dynamodb_tooling_language_groups_table: tooling_language_groups

# Internal Routes
language_server_url: ws://local.exercism.io:3023
spi_url: http://local.exercism.io:3020
tooling_orchestrator_url: http://local.exercism.io:3021

# MySQL
mysql_master_endpoint: localhost
mysql_socket: /tmp/mysql.sock
mysql_port: null

# S3 Config
aws_submissions_bucket: exercism-staging-submissions
aws_tooling_jobs_bucket: exercism-staging-tooling-jobs

# Sidekiq Config
sidekiq_redis_url: redis://127.0.0.1:6379/2
